---
name: interface
version: 0.01
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Declare support for an interface
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=interface
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  latest: 0.02
provides:
  interface:
    file: lib/interface.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
